CREATE TABLE IF NOT EXISTS USERS
(
	id           VARCHAR(42) PRIMARY KEY,
	name         VARCHAR(12) UNIQUE,
	image        VARCHAR(100),
	pool         VARCHAR(100),
	lang         VARCHAR(3) DEFAULT 'fr',
	active       TIMESTAMP  DEFAULT 0
);

CREATE TABLE IF NOT EXISTS COOKIES
(
	id       INTEGER PRIMARY KEY AUTOINCREMENT,
	userid   INTEGER,
	uuid     VARCHAR(65) UNIQUE,
	name     VARCHAR(40) DEFAULT NULL,
	creation TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (userid) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
	id       INTEGER PRIMARY KEY AUTOINCREMENT,
	who      INTEGER,
	has      INTEGER,
	relation INTEGER DEFAULT 0,
	UNIQUE (who, has),
	FOREIGN KEY (who) REFERENCES USERS (id),
	FOREIGN KEY (has) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS DEAD_PC
(
	id      INTEGER PRIMARY KEY AUTOINCREMENT,
	issuer  INTEGER,
	station VARCHAR(8),
	issue   INTEGER,
	solved  INTEGER   DEFAULT 0,
	since   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (issuer, station),
	FOREIGN KEY (issuer) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS PROFILES
(
	userid  INTEGER PRIMARY KEY REFERENCES USERS (id),
	website TEXT        DEFAULT '',
	github  TEXT        DEFAULT '',
	discord VARCHAR(40) DEFAULT '',
	recit   TEXT        DEFAULT ''
);

CREATE TABLE IF NOT EXISTS MODULAR_ISSUE
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    module     TEXT NOT NULL,
    computer   TEXT NOT NULL,
    data       TEXT,
    text       TEXT,
    icon_html  TEXT      DEFAULT '',
    severity   INTEGER   DEFAULT 0,
    latest     INTEGER   DEFAULT 1,
    since      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BAN_LIST
(
	id     INTEGER PRIMARY KEY AUTOINCREMENT,
	userid INTEGER,
	reason TEXT,
	since  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (userid) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS THEME
(
	userid     INTEGER PRIMARY KEY,
	javascript TEXT    DEFAULT NULL,
	css        TEXT    DEFAULT NULL,
	enabled    INTEGER DEFAULT 0,
	FOREIGN KEY (userid) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS MATES
(
	id             INTEGER PRIMARY KEY AUTOINCREMENT,
	project        TEXT,
	created        DATETIME DEFAULT CURRENT_TIMESTAMP,
	creator_id     INTEGER,
	people         INTEGER,
	deadline       TEXT     DEFAULT NULL,
	progress       INTEGER  DEFAULT 0,
	quick_contacts TEXT,
	mates          TEXT,
	description    TEXT,
	contact        TEXT,
	UNIQUE (project, creator_id),
	FOREIGN KEY (creator_id) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS SHADOW_BAN
(
	id       INTEGER PRIMARY KEY AUTOINCREMENT,
	user     INTEGER,
	offender INTEGER,
	reason   TEXT DEFAULT '',
	UNIQUE (user, offender),
	FOREIGN KEY (user) REFERENCES USERS (id),
	FOREIGN KEY (offender) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS PERMISSIONS
(
	user_id  INTEGER PRIMARY KEY,
	level    INTEGER DEFAULT 0,
	show_tag INTEGER DEFAULT 0,
	tag      TEXT    DEFAULT 'admin'
);

CREATE TABLE IF NOT EXISTS PISCINES
(
	id      INTEGER PRIMARY KEY,
	cluster TEXT
);

CREATE TABLE IF NOT EXISTS SILENTS
(
	id      INTEGER PRIMARY KEY,
	cluster TEXT
);

CREATE TABLE IF NOT EXISTS MESSAGES
(
	id        INTEGER PRIMARY KEY AUTOINCREMENT,
	author    INTEGER,
	dest      INTEGER,
	content   TEXT,
	anonymous INTEGER   DEFAULT 0,
	read      INTEGER   DEFAULT 0,
	created   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (author) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS SPECIAL_USERS
(
	sp_id         INTEGER PRIMARY KEY AUTOINCREMENT,
	sp_tag        TEXT,
	sp_tag_style  TEXT,
	sp_author     TEXT,
	sp_send_key   TEXT UNIQUE
);
